# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: blog-tai-project.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
    client:
        service-url:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
#        type: com.zaxxer.hikari.HikariDataSource
#        url: ${JDBC_DATABASE_URL}
#        username: ${JDBC_DATABASE_USERNAME}
#        password: ${JDBC_DATABASE_PASSWORD}
#        hikari:
#            maximumPoolSize: 8
        type: com.zaxxer.hikari.HikariDataSource
        url: r4919aobtbi97j46.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
        username: ydwhfbpx12lomm14
        password: lowvec9sseuwz8d2
        hikari:
            maximumPoolSize: 8
